language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t nkagale/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nkagale/docker-react npm run test -- --coverage
