language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t nkagale/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nkagale/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react-app"
    env: "DockerReactApp-env"
    bucket_name: "elasticbeanstalk-us-east-1-571398498870"
    bucket_path: "docker-react-app"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
